### ISSUE TITLE
Publish override might be incomplete

### ISSUE THREAD

**Issue by zimme** [peerlibrary/meteor-publish-context#1]
I just had a look at the `Meteor.publish` override code and it looks like it doesn't take the following format of `Meteor.publish` into account.
```js
Meteor.publish({
  allPosts() {
    const userId = this.userId;
    return userId ? Posts.find({ userId }) : this.ready();
});
```
Just as with `Meteor.methods`, `Meteor.publish` allows the developer to give it an object.

**Comment by mitar** [comment]
Thanks!
